# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lab6.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nlab6.proto\x12\nrouteguide\"\x1d\n\x05\x61\x64\x64_m\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x12\n\x05\x61\x64\x64_r\x12\t\n\x01\x61\x18\x01 \x01(\x05\"\x19\n\nrawImage_m\x12\x0b\n\x03img\x18\x01 \x01(\x0c\"\"\n\nrawImage_r\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"$\n\x0c\x64otProduct_m\x12\t\n\x01\x61\x18\x01 \x03(\x02\x12\t\n\x01\x62\x18\x02 \x03(\x02\"\x19\n\x0c\x64otProduct_r\x12\t\n\x01\x61\x18\x01 \x01(\x02\"\x1a\n\x0bjsonImage_m\x12\x0b\n\x03img\x18\x01 \x01(\t\"#\n\x0bjsonImage_r\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\x32\xfe\x01\n\nRouteGuide\x12-\n\x03\x61\x64\x64\x12\x11.routeguide.add_m\x1a\x11.routeguide.add_r\"\x00\x12<\n\x08rawImage\x12\x16.routeguide.rawImage_m\x1a\x16.routeguide.rawImage_r\"\x00\x12\x42\n\ndotProduct\x12\x18.routeguide.dotProduct_m\x1a\x18.routeguide.dotProduct_r\"\x00\x12?\n\tjsonImage\x12\x17.routeguide.jsonImage_m\x1a\x17.routeguide.jsonImage_r\"\x00\x42\x36\n\x1bio.grpc.examples.routeguideB\x0fRouteGuideProtoP\x01\xa2\x02\x03RTGb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lab6_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033io.grpc.examples.routeguideB\017RouteGuideProtoP\001\242\002\003RTG'
  _ADD_M._serialized_start=26
  _ADD_M._serialized_end=55
  _ADD_R._serialized_start=57
  _ADD_R._serialized_end=75
  _RAWIMAGE_M._serialized_start=77
  _RAWIMAGE_M._serialized_end=102
  _RAWIMAGE_R._serialized_start=104
  _RAWIMAGE_R._serialized_end=138
  _DOTPRODUCT_M._serialized_start=140
  _DOTPRODUCT_M._serialized_end=176
  _DOTPRODUCT_R._serialized_start=178
  _DOTPRODUCT_R._serialized_end=203
  _JSONIMAGE_M._serialized_start=205
  _JSONIMAGE_M._serialized_end=231
  _JSONIMAGE_R._serialized_start=233
  _JSONIMAGE_R._serialized_end=268
  _ROUTEGUIDE._serialized_start=271
  _ROUTEGUIDE._serialized_end=525
# @@protoc_insertion_point(module_scope)
